### ISSUE TITLE
Launch the marked VIs in the right application context.

### ISSUE THREAD

**Issue by JayKayAce** [gcentral/top-level-launcher#14]
When running the top level VI, the toolkit must set the correct context. 
![image](https://github.com/user-attachments/assets/014927a1-7626-4980-a9cc-218ba131db33)

The suggestion from @dnattinger is to add the following:

That code should be using the App Reference of the context (My Computer, e.g.) that owns the Top-Level VI. Right now the app reference to Open VI Reference is unwired, which means it is opening it in the NI.LV.Editor context (i.e. where Quick Drop plugins run), so you've got the VI open in two contexts... that's probably why it's broken.

This issue was reported by @neilpate

**Comment by crossrulz** [comment]
The context the tool is running in is not the problem here. All QD plugins are ran from the NI.LV.Editor context. The issue is in the Run Top Level.vi as the application context needs set when the VI to run is opened. It is also recommended to open the VI's front panel to make sure it will run. My non-cleaned up solution is as follows:
![Run Top Level_BD](https://github.com/user-attachments/assets/de991218-e0fc-4e00-852c-fb9da44864df)

**Comment by crossrulz** [comment]
I have an updated test project that duplicates the issue found and proposed solution put together. I'll give others a chance to provide feedback (here and on Discord) before submitting a pull request.

**Comment by JayKayAce** [comment]
Fixed by #15
